services:
  - docker

env:
  global:
    - DOCKER_REPO="oanhnn/go-workbench"

before_script:
  - docker info
  - if [[ ${TRAVIS_BRANCH} == "master" ]]; then
      export IMAGE_TAG="latest";
    else
      export IMAGE_TAG=${TRAVIS_BRANCH};
    fi
  - export IMAGE_NAME="oanhnn/go-workbench:${IMAGE_TAG}"

script:
  - ./hooks/build
