services:
  - docker

env:
  global:
    - DOCKER_REPO="oanhnn/go-workbench"
  matrix:
    - GO_VERSION="1.11"

before_script:
  - docker info

script:
  - export IMAGE_NAME="oanhnn/go-workbench:${GO_VERSION}"
  - cd $GO_VERSION
  - ./hooks/build
